name: weather_app
description: Flutter application to look up weather for any location.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pedantic: ^1.11.0
  http: ^0.12.0
  geolocator: ^3.0.1
  flutter_spinkit: ^5.0.0
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  built_value: ^8.0.3
  built_collection: ^5.0.0
  freezed_annotation: ^0.14.1
  redux_epics: ^0.14.0
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.0
  built_value_generator: ^8.0.3
  freezed: ^0.14.1
  analyzer: any

flutter:


  uses-material-design: true

